### ISSUE TITLE
Convenience function for splitting weights and biases

### ISSUE THREAD

**Issue by korsbo** [PumasAI/SimpleChains.jl#55] opened 2022-04-21 12:04 UTC
Given a vector of parameters `p` to be used with a SimpleChain `sc`, it could sometimes be useful to figure out which of the elements of `p` will be used for weights and which will be used as biases. 

I'm currently missing it a bit myself when I'm defining a regularised loss function to be used with an external optimiser.

**Comment by ChrisRackauckas** [comment] 2022-04-21 12:29
This is a duplicate of https://github.com/PumasAI/SimpleChains.jl/issues/24

**Closed** 2022-04-21 12:30 UTC
