### ISSUE TITLE
`init_params` bug

### ISSUE THREAD

**Issue by korsbo** [PumasAI/SimpleChains.jl#112] opened 2022-09-28 14:35 UTC
```julia
using SimpleChains
using Statistics

sc= SimpleChain(
static(2),
TurboDense(4, tanh),
TurboDense(4, tanh),
TurboDense(3, identity)
)

init_params(sc, Float64) |> std
init_params(sc, Float32) |> std
```

Running this a few times, I get that the `Float64` method has a std around 0.5 while the `Float32` one has an std of around 1.

This is with main as of two days ago (before merging #110)

**Comment by chriselrod** [comment] 2022-09-28 14:58
```julia
julia> f32 = [std(SimpleChains.init_params(sc, Float32)) for _ in 1:10_000];

julia> f64 = [std(SimpleChains.init_params(sc, Float64)) for _ in 1:10_000];

julia> mean(f32)
0.29680106f0

julia> mean(f64)
0.4596680785000013
```

**Comment by korsbo** [comment] 2022-09-28 15:05
huh, that is not what I got. But it still looks strange that the two would be different.

**Comment by chriselrod** [comment] 2022-09-28 15:05
Yes, still definitely wrong. This was on latest `main`.

**Comment by korsbo** [comment] 2022-09-28 15:10
We might want to be careful here though. I've found some misuses of `glorot_normal!` both in the tests of this package as well as in other packages where the fan-in fan-out got lost as the input was flattened before passed. It'd be good to test that `init_param` correctly uses glorot normal (0 biases) by at least manually comparing the statistics from a bunch of runs with some other implementation.

**Comment by chriselrod** [comment] 2022-09-28 15:14
Locally, I've now added support for passing an `rng` object
```julia
julia> f32tl = [std(SimpleChains.init_params(sc, Float32, Random.default_rng())) for _ in 1:10_000];

julia> f64tl = [std(SimpleChains.init_params(sc, Float64, Random.default_rng())) for _ in 1:10_000];

julia> mean(f64tl)
0.4600335208066101

julia> mean(f32tl)
0.46095517f0
```

**Comment by chriselrod** [comment] 2022-09-28 15:15
> We might want to be careful here though. I've found some misuses of `glorot_normal!` both in the tests of this package as well as in other packages where the fan-in fan-out got lost as the input was flattened before passed. It'd be good to test that `init_param` correctly uses glorot normal (0 biases) by at least manually comparing the statistics from a bunch of runs with some other implementation.

While I suspect that nothing like this is the cause for the issues reported here (given my above comment), I do agree that this would be useful.

**Comment by chriselrod** [comment] 2022-09-28 15:25
Still, replacing
```julia
  randn!(rng, A, static(0), static(0), σ)
```
with
```julia
  randn!(rng, A)
  A .*= σ
  return A
```
also yields the expected 0.46.

**Comment by chriselrod** [comment] 2022-09-28 15:31
Using a vector length of 15 instead of 2048 with the same VectorizedRNG example above can reproduce the problem.

**Comment by chriselrod** [comment] 2022-09-28 16:00
Fixed by

**Closed by chriselrod** 2022-09-28 16:00 UTC
Labels: bug
